
#
# This LookML file was generated by AtScale on 2022-03-07T21:23:07.908711Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Looker Demo

connection: "looker-demo"
label: "Looker Demo"


include: "/views/Looker_Demo.view.lkml"


explore: Store_and_Web_Sales_Analysis {
  label: "Looker Demo"
}
