
#
# This LookML file was generated by AtScale on 2022-01-25T16:10:14.817595Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_YN

connection: "atscale-test"
label: "Workshop_YN"


include: "/views/Workshop__KLN.view.lkml"


explore: Workshop_KLN {
  label: "Workshop_KLN"
}
